### PR TITLE
 Fix for linker issue for _fopen_ascii

### PR DESCRIPTION
**Pull request by HarithaIBM**
Fix for linker error :

IEW2456E 9207 SYMBOL __fopen_ascii UNRESOLVED

Resolution:

Added libs for generation of lesskey and related targets as well

### CODE REVIEW

**Comment by HarithaIBM** [comment]
@IgorTodorovskiIBM @MikeFultonDev Please review the changes, thank you!

**Comment by AnthonyGiorgio** [comment]
I didn't see this linker error.  Which compiler was producing it?

**Comment by IgorTodorovskiIBM** [comment]
It should be xlclang. This is a result of us overriding fopen in zoslib and less not being able to find the zoslib.a file.

**Comment by HarithaIBM** [comment]
Thank you for comments and review, merging it!

**Pull request merged**
